  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: "${module.eks.certificate_authority_data}"
      server: "${module.eks.cluster_endpoint}"
    name: "${module.eks.cluster_name}"
  contexts:
  - context:
      cluster: "${module.eks.cluster_name}"
      user: "${module.eks.cluster_name}-user"
    name: "${module.eks.cluster_name}"
  current-context: "${module.eks.cluster_name}"
  kind: Config
  preferences: {}
  users:
  - name: "${module.eks.cluster_name}-user"
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws
        args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "${module.eks.cluster_name}"